server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址,写死了无法负载均衡
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址，配置动态路由
          predicates:
            - Path=/payment/get*/**             # 断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service      #匹配后提供服务的路由地址
          filters:
          #- AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加X-Request-Id=1024
          predicates:
            - Path=/payment/**              # 断言，路径相匹配的进行路由
            #- After=2021-06-22T20:56:29.501+08:00[Asia/Shanghai]  #在此时间之后才能访问，秒杀，活动开始
            #- Before   - Between
            #在cmd里：命令curl http://localhost:9527/payment/lb --cookie "username"=zzyy，模拟请求
            #- Cookie=username,zzyy
            #命令：curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
            #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性，值为整数的正则表达式
            #命令：curl http://localhost:9527/payment/lb -H "Host: www.atguigu.com"
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数username且值为整数
      discovery:
        locator:
          enabled: true           #开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service   #服务端名称
